import os

# Snowflake configuration
SNOWFLAKE_USER = os.getenv('SNOWFLAKE_USER')
SNOWFLAKE_PASSWORD = os.getenv('SNOWFLAKE_PASSWORD')
SNOWFLAKE_ACCOUNT = os.getenv('SNOWFLAKE_ACCOUNT')
SNOWFLAKE_DATABASE = os.getenv('SNOWFLAKE_DATABASE')
SNOWFLAKE_SCHEMA = os.getenv('SNOWFLAKE_SCHEMA')
SNOWFLAKE_GAS_STATION_TABLE = 'gas_stations'
SNOWFLAKE_DISCOUNT_TABLE = 'DISCOUNT'

# Excel file configuration
EXCEL_FILE_PATH = os.getenv('EXCEL_FILE_PATH')
EXCEL_FILE_NAME = 'discount.xlsx'